version: '2'
services:
  two-dollars:
    build:
      context: ms-dollar-two-days
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - dollar-quote-api
  dollar-quote-api:
    build:
      context: ms-dollar-quote-bcb
      dockerfile: Dockerfile
    ports:
      - 8082:8082


